finish torrent history
PBH-BTN/PeerBanHelper pull request #518
Opened 2024-09-23 07:52 UTC by Gaojianli

2024-09-23 08:18 UTC, Ghost-chu requested changes
![image](https://github.com/user-attachments/assets/897bb92a-8828-4539-a3c1-cf903968f52b)

i18n 也爆了

2024-09-23 08:18 UTC, Ghost-chu commented on webui/src/api/model/data.ts
确实 IP 的 GeoIP 信息

2024-09-23 08:18 UTC, Ghost-chu commented on webui/src/views/data-view/locale/es-US.ts
es-US.ts 是个什么语言，没见过

2024-09-23 08:18 UTC, Ghost-chu commented on webui/src/views/data-view/torrentList/components/accessHistoryModal.vue
> +</script>
@Gaojianli 这里的 flags 可能为空

2024-09-23 08:18 UTC, Ghost-chu commented on webui/src/views/data-view/torrentList/locale/zh-CN.ts
> +  'page.torrentList.description': '这个页面展示 PeerBanHelpe 在运行过程中观测到的种子数据。',
typo

2024-09-23 11:43 UTC, Gaojianli commented on webui/src/views/data-view/torrentList/components/accessHistoryModal.vue
> +</script>
有v-if

2024-09-24 10:33 UTC, Ghost-chu commented
http://localhost:5173/torrentHistory 只能查询访问历史，不能查询封禁历史。

当 PBH Plus 未激活的时候，页面会卡住而没有提示信息。

![1fc645a563553bb6a0586b6bcacd9239](https://github.com/user-attachments/assets/5d53414f-39d0-4a83-af3c-e234b3fcda0a)

2024-09-24 10:34 UTC, Ghost-chu requested changes
torrentHistory 没有查询封禁历史的按钮

2024-09-24 10:34 UTC, Ghost-chu commented on webui/src/views/data-view/torrentList/locale/zh-CN.ts
> +  'page.torrentList.description': '这个页面展示 PeerBanHelpe 在运行过程中观测到的种子数据。',
typo

2024-09-24 10:55 UTC, Gaojianli commented
> http://localhost:5173/torrentHistory 只能查询访问历史，不能查询封禁历史。
> 
> 当 PBH Plus 未激活的时候，页面会卡住而没有提示信息。
> 
> ![1fc645a563553bb6a0586b6bcacd9239](https://private-user-images.githubusercontent.com/30802565/370246021-5d53414f-39d0-4a83-af3c-e234b3fcda0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNzU2MDYsIm5iZiI6MTcyNzE3NTMwNiwicGF0aCI6Ii8zMDgwMjU2NS8zNzAyNDYwMjEtNWQ1MzQxNGYtMzlkMC00YTgzLWFmM2MtZTIzNGIzZmNkYTBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDEwNTUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyMzZiNjllODIzYzJjZWE4Yzg4ZDU4NDI4N2U5ZmNlZjMyYTU2MWQ5ZGRiZTk3NzNiOTE2YmEyZDRmNWM4ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.L1jqAgmHAxJlSIh5n-1ruxwc0lWO6jRhW036aeRGBH0)

![image](https://github.com/user-attachments/assets/764d300b-34d4-4897-8ca0-2908e56ce29f)

2024-09-24 13:42 UTC, Ghost-chu requested changes
![image](https://github.com/user-attachments/assets/0afb8f19-ee48-45c4-9d96-121a4bc88188)

IP 列丢了

2024-09-24 14:02 UTC, Ghost-chu commented
我调整了一下接口，因为我发现返回 PEER_RECORD_NOT_FOUND 前端就直接趴窝了
所以现在查询记录如果不存在，时间会返回 -1，次数都是 0，并允许用户查询 IPDB。

![6723f28104d78523e27760f0faa9cdd9](https://github.com/user-attachments/assets/ba457a7f-094d-4830-ae1e-2d35ad251877)

这个页面还有另外一个问题，就是如果查询接口返回了错误信息，重试查询的时候，即使服务器重新返回了正确响应，它也再也不更新了。

2024-09-24 14:04 UTC, Ghost-chu commented on webui/src/service/data.ts
> +}
@Gaojianli 这里是不是有个 typo

2024-09-24 14:07 UTC, Ghost-chu commented on webui/src/views/data-view/torrentList/components/accessHistoryModal.vue
> +            </a-tooltip>
@Gaojianli 需要更改

2024-09-25 04:49 UTC, Gaojianli commented
> 我调整了一下接口，因为我发现返回 PEER_RECORD_NOT_FOUND 前端就直接趴窝了 所以现在查询记录如果不存在，时间会返回 -1，次数都是 0，并允许用户查询 IPDB。
> 
> ![6723f28104d78523e27760f0faa9cdd9](https://private-user-images.githubusercontent.com/30802565/370317760-ba457a7f-094d-4830-ae1e-2d35ad251877.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNDAwMDksIm5iZiI6MTcyNzIzOTcwOSwicGF0aCI6Ii8zMDgwMjU2NS8zNzAzMTc3NjAtYmE0NTdhN2YtMDk0ZC00ODMwLWFlMWUtMmQzNWFkMjUxODc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDA0NDgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3M2FjZGRhODY2MGI1NzJjZTgzZTI2NDMyYjMxNDM4MTU4MzUwMWViMTY4YzFhYjM4ODhkM2Q2ZWEzNzZlNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9zXwlbtEThU1bJsKCnZkD18T4xG1zI5ByDZpedmS8mU)
> 
> 这个页面还有另外一个问题，就是如果查询接口返回了错误信息，重试查询的时候，即使服务器重新返回了正确响应，它也再也不更新了。

因为没有定义没找到，请把没找到的case直接返回空data吧

2024-09-25 05:03 UTC, merged