V7
PBH-BTN/PeerBanHelper pull request #608
Opened 2024-10-18 06:46 UTC by Gaojianli

2024-10-18 06:48 UTC, Gaojianli commented
@coderabbitai pause

2024-10-20 12:40 UTC, Ghost-chu commented on src/main/java/com/ghostchu/peerbanhelper/module/impl/webapi/PBHGeneralController.java
> +            .create();
It have custom ObjectToNumberStrategy so we can't reuse it

2024-10-20 12:42 UTC, Ghost-chu commented
@coderabbitai review

2024-10-21 18:33 UTC, Gaojianli commented on src/main/java/com/ghostchu/peerbanhelper/module/impl/webapi/PBHGeneralController.java
> +        network.put("reverse_proxy", !Objects.equals(clientIp, userIp));
这里还需要判断几个header x-forwarded-for x-real-ip x-forwared-host

2024-10-21 18:33 UTC, Gaojianli commented on src/main/java/com/ghostchu/peerbanhelper/module/impl/webapi/PBHGeneralController.java
> +        network.put("reverse_proxy", !Objects.equals(clientIp, userIp));
@paulzzh

2024-10-22 12:13 UTC, Ghost-chu commented on src/main/java/com/ghostchu/peerbanhelper/module/impl/webapi/PBHGeneralController.java
> +        network.put("reverse_proxy", !Objects.equals(clientIp, userIp));
成了

2024-10-25 07:02 UTC, Gaojianli commented
@coderabbitai 开始review

2024-10-26 06:49 UTC, Ghost-chu commented
@coderabbitai review

2024-10-26 06:54 UTC, Ghost-chu commented
@Gaojianli 
![image](https://github.com/user-attachments/assets/3052701f-83b1-4cdd-9a72-ba0ea8bf8cab)

这个弹窗的位置正好挡住了警报按钮，而且这个弹窗说能点但实际上点不动

2024-10-26 16:24 UTC, Gaojianli commented
> @Gaojianli ![image](https://private-user-images.githubusercontent.com/30802565/380370388-3052701f-83b1-4cdd-9a72-ba0ea8bf8cab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NjAwOTMsIm5iZiI6MTcyOTk1OTc5MywicGF0aCI6Ii8zMDgwMjU2NS8zODAzNzAzODgtMzA1MjcwMWYtODNiMS00Y2RkLTlhNzItYmEwZWE4YmY4Y2FiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDE2MjMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxZDcwYjAwNzBmZjRmMzAzMGRjODY3MTE1MjQwOGE0NTMxNmMxNDA4OGVmMjA0ZDdlMjVkOGNmNDAzZDgwOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aCXMGVFWQ9AsIReYqEwRm1Njq2tKt0SXo0IOmaqJ0bU)
> 
> 这个弹窗的位置正好挡住了警报按钮，而且这个弹窗说能点但实际上点不动

本来就没说真的让点

2024-10-26 16:25 UTC, Gaojianli commented
With the development of new features completed, the V7 version is now in the feature freeze phase

2024-10-26 16:26 UTC, Ghost-chu commented
> With the development of new features completed, the V7 version is now in the feature freeze phase

高老师，我的 JVM 的内存情况加了吗



> > @Gaojianli ![image](https://private-user-images.githubusercontent.com/30802565/380370388-3052701f-83b1-4cdd-9a72-ba0ea8bf8cab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NjAwOTMsIm5iZiI6MTcyOTk1OTc5MywicGF0aCI6Ii8zMDgwMjU2NS8zODAzNzAzODgtMzA1MjcwMWYtODNiMS00Y2RkLTlhNzItYmEwZWE4YmY4Y2FiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDE2MjMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxZDcwYjAwNzBmZjRmMzAzMGRjODY3MTE1MjQwOGE0NTMxNmMxNDA4OGVmMjA0ZDdlMjVkOGNmNDAzZDgwOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aCXMGVFWQ9AsIReYqEwRm1Njq2tKt0SXo0IOmaqJ0bU)
> > 这个弹窗的位置正好挡住了警报按钮，而且这个弹窗说能点但实际上点不动
> 
> 本来就没说真的让点

容易引起误解，建议修改文案，然后往下面挪一点，或者让它真的能点

2024-10-26 16:33 UTC, Ghost-chu requested changes
* [ ] 缺少 JVM 的内存信息
* [ ] 需要让日志线程不那么五彩斑斓
* [ ] 警告浮窗的文案需要修改或者让它真的能点，除非之后有人原意每天答疑这个问题

2024-10-26 18:38 UTC, merged