PCB 支持检查未完成/不完整任务的过量下载
PBH-BTN/PeerBanHelper pull request #748
Opened 2024-11-16 19:34 UTC by paulzzh

size 为种子的总大小，用于进度计算和判断过量 #700 
新增 completedSize 为**任务中已完成的数据量**(这些内容可被做种上传) fix #746 
可以应对以下情况：
- 下载器就是种子发布者，此时下载量为0，但是已完成的数据量为种子大小 (因此不能使用下载量判断)
- 勾选了很大的文件，但是无法下载到，一些小文件已被下载，此时这些小文件被放血 (因此不能使用勾选大小)
- 勾选了一些小文件，但是种子整体很大，触发进度检查和下载过量要很久 #746 

下载器适配：
- [x] qb：支持(completed)
- [x] bc：支持(selected_downloaded_size)
- [ ] tr：暂时不支持，想不出来怎么写
- [ ] [BiglyBT](https://github.com/PBH-BTN/PBH-Adapter-BiglyBT)：需要适配器支持，看了半天没找到想要的接口
- [ ] [Deluge](https://github.com/PBH-BTN/PBH-Adapter-Deluge)：适配器已支持，需要合并 PBH-BTN/PBH-Adapter-Deluge#1

2024-11-17 10:46 UTC, Ghost-chu commented
建议此功能添加一个启动参数 flag 允许用户禁用这个 Feat

2024-11-17 11:08 UTC, paulzzh commented on src/main/java/com/ghostchu/peerbanhelper/module/impl/rule/ProgressCheatBlocker.java
> +            final long completedSize = torrent.getCompletedSize();
long referenceSize = (completedSize > 0 && actualUploaded > completedSize) ? completedSize : torrentSize
completedSize必须大于0才会启用这个功能

2024-11-18 03:23 UTC, Gaojianli commented on src/main/java/com/ghostchu/peerbanhelper/module/impl/rule/ProgressCheatBlocker.java
> +                long referenceSize = (System.getProperty("pbh.pcb.disable-completed-excessive") == null && completedSize > 0 && actualUploaded > completedSize) ? completedSize : torrentSize;
更新一下配置文件，这样前端才能增加对应的配置项

2024-11-18 03:28 UTC, Ghost-chu commented on src/main/java/com/ghostchu/peerbanhelper/module/impl/rule/ProgressCheatBlocker.java
> +                long referenceSize = (System.getProperty("pbh.pcb.disable-completed-excessive") == null && completedSize > 0 && actualUploaded > completedSize) ? completedSize : torrentSize;
为保持BTN数据一致性，此功能应总是开启。

这个开关的作用完全是为了防止发版之后功能翻车，用户可以在不更新版本的情况下还原行为而设计的。

2024-11-19 02:32 UTC, Ghost-chu approved these changes

2024-11-19 02:33 UTC, Ghost-chu requested changes
话说 PCB 的提示信息那些是不是也应该进行修改？

2024-11-20 04:59 UTC, Ghost-chu requested changes
我认为不是改成资源就足够的，应该考虑改成 `种子总大小: 128MB (38.9MB 已下载)` 这种，不然可能会让用户感到困惑。

2024-11-20 04:59 UTC, Ghost-chu commented
> 我认为不是改成资源就足够的，应该考虑改成 `种子总大小: 128MB (38.9MB 已下载)` 这种，不然可能会让用户感到困惑。  
如果种子已经是完全下载完的，可以不显示（XXX 已下载）这一部分

2024-11-20 07:27 UTC, Ghost-chu commented
> 其中qB无法处理 已经下载了的大文件，但又取消勾选了的情况，可能造成误封禁 (被取消的内容仍可提供上传 但completed会变小 因此可上传量会大于completed 可能会误判过量下载)

可以考虑请求种子文件列表获取更详细的信息。

2024-11-20 22:38 UTC, paulzzh commented on src/main/java/com/ghostchu/peerbanhelper/module/impl/rule/ProgressCheatBlocker.java
> +                    }
no

2024-11-22 07:38 UTC, Ghost-chu approved these changes

2024-11-22 13:21 UTC, merged