v7.2
PBH-BTN/PeerBanHelper pull request #800
Opened 2024-12-06 12:46 UTC by Ghost-chu

## 发版前检查列表

* [ ] https://github.com/PBH-BTN/PeerBanHelper/issues/795

## 需要注意

本版本的 docker-compose.yml 包含新的更改，如果您正在使用 Docker Compose 部署，请更新您的 docker-compose.yml 文件。

对于群晖套件用户，升级套件时相关脚本将自动更新。

## 反吸血算法改进

改进了对 [BEP-0021 Extension for partial seeds](https://www.bittorrent.org/beps/bep_0021.html) 规范的支持，现在能够对下列情况做出正确的过量下载/进度回退的反吸血判定：

* 种子处于下载状态，部分文件没有完整下载
* 用户/Peer在 “内容” 选项卡中只选择了部分文件下载，而不是整个完整的 torrent (BEP-0021)
* 下载过程中出现错误，导致下载停止，进入了仅上传状态（如 I/O 错误，或者在下载 torrent 过程中磁盘空间不足）

现在 PeerBanHelper 的进度反作弊能够正确处理上面列出的情况。 @paulzzh 

## 可显示/隐藏的图表项

现在图表页面可选择显示或者隐藏特定的图表。@Gaojianli

![image](https://github.com/user-attachments/assets/f90ab8ba-d11c-45bd-bee0-b29d267325cf)

## IPFS/IPNS 规则订阅支持

作为 #622 的一部分，本次 v7.2 版本中新增了 IPFS/IPNS 去中心化网络支持。[IPFS（星际文件系统）](https://ipfs.tech/) 是一个类似 BitTorrent 的完全去中心化点到点超媒体传输协议，而 [IPNS](https://docs.ipfs.tech/concepts/ipns/) 则充当 IPFS 网络中的 DNS。

要使用 IPFS/IPNS 规则订阅，则需要部署 Kubo IPFS 客户端，并在实验室中启用 IPFS 实验。启用后，您就可以使用 IPFS 和 IPNS 协议地址来添加订阅。

您可以在配置文件中修改 Kubo RPC 地址为您自行安装的 Kubo IPFS 客户端，或者使用新的 docker-compose.yml 部署，将会自动配置 IPFS 客户端。

* 对于 IPFS 来说，你需要使用 `ipfs://CID` 格式的 URL，但缺点是每个文件被提交到 IPFS 后都无法再次被修改
* 您也可以使用 IPNS，IPNS 是可修改的，并可以指向任意 CID，格式为 `ipns://ID`，你可以在 IPFS Desktop 中将不同的文件发布到同一个 IPNS 上来完成更新操作

同时，PeerBanHelper 也会每隔 1 个小时（可修改）将自身的 Banlist 发布到 IPFS 和 IPNS 上，IPNS 地址可在 IPFS 客户端上看到。如果您的 IPFS 客户端连接了多个 PeerBanHelper 客户端，则您可以通过后缀（安装ID）来识别不同的 PeerBanHelper 客户端。

![Kubo Client IPNS](https://github.com/user-attachments/assets/9067943f-9451-4df8-9065-a9b27378e8f5)

使用 IPFS 网络可以做到人人都能创建合订阅规则，且无需购买服务器。使用的人越多，则帮助你一起分发规则的人也越多。 @Ghost-chu 

## PeerBanHelper Labs

欢迎来到 PeerBanHelper 实验室！我们有时会对 PeerBanHelper 的一些功能做出实验性的更改。这些实验正在进行中，有的则可能被放弃。我们希望其中的多数会获得您的反馈意见，得以改进，并最终成为 PeerBanHelper 的一部分。PeerBanHelper 实验室的作用就在于此。

每个实验推出时都会随机的在一部分用户的 PeerBanHelper 上启用，以便获得新功能的反馈。但如果新功能的对您造成了困扰/或者想要提前尝鲜测试，您也可以随时在 “实验室” 菜单中手动开启关闭实验项目。@Ghost-chu 

![PeerBanHelper Labs](https://github.com/user-attachments/assets/371f772b-2b7d-481c-aa44-7983503d889f)

## install4j 自动更新支持

被大家心心念念的 Windows/Linux 平台的 install4j 自动更新的支持现已到来。对使用安装程序安装的 PeerBanHelper，在本次更新后将会添加自动更新功能。每次启动 PeerBanHelper 时，更新程序会在后台检查并下载更新，并在下一次启动时安装新的更新。

您也可以通过开始菜单中新增的 “PeerBanHelper 检查更新” 程序来手动检查更新：

![image](https://github.com/user-attachments/assets/378ea19a-f020-43b9-93cd-9c11f9fd08f0)

![de9aa83ed64e53850d3abcc10b49eb35](https://github.com/user-attachments/assets/30006a7c-63cd-4856-a7cd-210e1ca6e77c)

对于非 install4j 安装程序安装的 PeerBanHelper：

* Docker：可使用 WatchTower 自动更新
* 群晖套件：继续由群晖的套件中心提供更新
* .deb 包：由用户自行管理更新

@Ghost-chu 

## DEB 安装包改进

感谢 @Anuskuss。本次更新后，使用 DEB 安装包安装 PeerBanHepler 的用户将会将数据文件和 PBH 主程序安装到更合适的位置。本次更新也同时改进了日志记录功能。#732

## 性能优化

* 改进了加载 BTN 规则时产生的内存尖峰，避免极端情况下可能导致 OOM 的问题 @Ghost-chu 
* 改进了例外列表 IP 判断的性能和内存占用 @Ghost-chu 

## PBH Plus 许可证更改

在过去只有在爱发电上捐赠我们的用户可以使用 PBH Plus 的捐赠功能，但我们认为这可能有悖于非营利软件的定义。因此在 v7.2 版本中，我们添加了一个 “我不想捐赠” 的按钮，允许直接激活 PBH Plus 许可证而无需捐赠。

通过这种方式激活的 PBH Plus 许可证在功能上与捐赠用户的许可证完全相同，但有效期只有 15 天，且不会显示捐赠感谢信息。当许可证到期后，您可以重复相同步骤，再次点击 “我不想捐赠” 创建新的循环许可证。

![image](https://github.com/user-attachments/assets/491b9116-6c23-42b1-b410-6f1e9dae0538)

如果 PeerBanHelper 确实有帮到您，仍然希望您考虑捐赠此项目。

2024-12-06 16:03 UTC, Ghost-chu commented
需要一阶段 review，快照已提交到测试组测试。

2024-12-06 16:06 UTC, Ghost-chu commented
@coderabbitai review

2024-12-07 08:53 UTC, Gaojianli commented
好耶，刚好800号

2024-12-07 18:20 UTC, Gaojianli commented
![image](https://github.com/user-attachments/assets/a03bc19f-5da3-48ac-824c-3c28e1f8aa56)
 english missing

2024-12-07 18:22 UTC, Ghost-chu commented
> ![image](https://private-user-images.githubusercontent.com/19235246/393540011-a03bc19f-5da3-48ac-824c-3c28e1f8aa56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1OTYwMTksIm5iZiI6MTczMzU5NTcxOSwicGF0aCI6Ii8xOTIzNTI0Ni8zOTM1NDAwMTEtYTAzYmMxOWYtNWRhMy00OGFjLTgyNGMtM2MyOGUxZjhhYTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDE4MjE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiMTllYTI0MzY5NTE3NTQ1MDVmNDhlZTA2YzFhNzQ3OGUyZDY4ODhlNGFmY2Y1ZjVmNmYzOWY2OWRlM2YxZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qPtJgAusGGqKeGWLlXi4cDqtjmYez9X5k5NyhnGFWh8) english missing @Ghost-chu

ChatGPT 对这些部分内容的配置文件部分翻译不是很好，出现格式错误，暂时搁置了

2024-12-08 11:20 UTC, paulzzh requested changes

2024-12-08 11:20 UTC, paulzzh commented on install4j/project.install4j
> +  <directoryPresets config="C:/Users/29088/OneDrive/文档/Database4.accdb.accdb" />
这是啥？

2024-12-08 11:20 UTC, paulzzh commented on pom.xml
> +    <version>7.2.0-Beta1</version>
正式发版记得改版本号

2024-12-08 11:20 UTC, paulzzh commented on src/main/java/com/ghostchu/peerbanhelper/util/PBHPortMapper.java
> +        this.network = NetworkGateway.create();
需要允许完全关闭此模块

2024-12-08 11:56 UTC, Ghost-chu commented on install4j/project.install4j
> +  <directoryPresets config="C:/Users/29088/OneDrive/文档/Database4.accdb.accdb" />
我也不是很清楚它为什么会在这里，这个之前应该删掉了，我现在在 install4j IDE 里面也看不到这个

2024-12-08 11:57 UTC, Ghost-chu commented on src/main/java/com/ghostchu/peerbanhelper/util/PBHPortMapper.java
> +        this.network = NetworkGateway.create();
我直接把它的@Component注释去掉了，这是段 unused code

2024-12-08 12:12 UTC, paulzzh requested changes

2024-12-08 12:12 UTC, paulzzh commented on webui/src/api/model/push.ts
> +  openId: string
这里sendkey和openid都应该是小写

2024-12-08 12:12 UTC, paulzzh commented on webui/src/api/model/push.ts
> +  chatId: string
这里chatid应该是小写

2024-12-09 05:21 UTC, Gaojianli commented
> > ![image](https://private-user-images.githubusercontent.com/19235246/393540011-a03bc19f-5da3-48ac-824c-3c28e1f8aa56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1OTYwMTksIm5iZiI6MTczMzU5NTcxOSwicGF0aCI6Ii8xOTIzNTI0Ni8zOTM1NDAwMTEtYTAzYmMxOWYtNWRhMy00OGFjLTgyNGMtM2MyOGUxZjhhYTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDE4MjE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiMTllYTI0MzY5NTE3NTQ1MDVmNDhlZTA2YzFhNzQ3OGUyZDY4ODhlNGFmY2Y1ZjVmNmYzOWY2OWRlM2YxZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qPtJgAusGGqKeGWLlXi4cDqtjmYez9X5k5NyhnGFWh8) english missing @Ghost-chu
> 
> ChatGPT 对这些部分内容的配置文件部分翻译不是很好，出现格式错误，暂时搁置了

分段翻译呗，别直接整个塞进去

2024-12-09 16:31 UTC, Ghost-chu commented
@Gaojianli @paulzzh review 下吧，没问题发版了

2024-12-10 08:06 UTC, Ghost-chu commented
@Gaojianli 新的更新日志功能需要在更新日志中提及

2024-12-10 08:07 UTC, Gaojianli commented
> @Gaojianli 新的更新日志功能需要在更新日志中提及

你往上翻翻呢

2024-12-10 08:08 UTC, Ghost-chu commented
> > @Gaojianli 新的更新日志功能需要在更新日志中提及
> 
> 你往上翻翻呢

我看见了，能发版吗

2024-12-10 15:51 UTC, merged