优化 PBH 语言文件的格式，规范表达
PBH-BTN/PeerBanHelper pull request #854
Opened 2024-12-29 12:37 UTC by CreeperAWA

主要是为中文与西文字符之间添加空格，规范表达（部分允许→容许）

2024-12-29 17:03 UTC, Ghost-chu commented
master hard reset 了一下，PR 需要 rebase 到 master 现在的 head

2024-12-30 08:33 UTC, Gaojianli commented on webui/src/locale/zh-CN.ts
> +  'service.networkErrorRetry.second': '{count} 秒',
中文数字后面需要加空格吗
`2秒` vs `2 秒`感觉怪怪的

2024-12-30 08:37 UTC, Gaojianli requested changes

2024-12-30 08:37 UTC, Gaojianli commented on webui/src/views/charts/locale/zh-CN.ts
> +  'page.charts.options.shortcut.30days': '最近 30 天',
间隙过大，会导致换行

2024-12-30 08:37 UTC, Gaojianli commented on webui/src/views/charts/locale/zh-CN.ts
> +  'page.charts.locked': '此图表需要激活 PeerBanHelper Plus 才能查看',
+是规范表达

2024-12-30 08:37 UTC, Gaojianli commented on webui/src/views/charts/locale/zh-CN.ts
> +  'page.charts.title.geoip': '位置与运营商 ',
why？

2024-12-30 08:37 UTC, Gaojianli commented on webui/src/views/dashboard/locale/zh-CN.ts
这个文件变更内容是什么

2024-12-30 08:37 UTC, Gaojianli commented on webui/src/views/data-view/torrentList/locale/zh-CN.ts
> -    '从开始或者上次对端重置数据后，上传/下载数据增量信息',
加空格太奇怪

2024-12-30 08:37 UTC, Gaojianli commented on webui/src/views/oobe/locale/zh-CN.ts
> +  'page.oobe.steps.welcome.docTips': '请在开始前阅读 {doc} 和 {privacy}',
此处是蓝色超链接，不能加空格

2024-12-30 08:37 UTC, Gaojianli commented on webui/src/views/rule-management/components/generic/locale/zh-CN.ts
> +  'page.rule_management.generic.description': '您可以在这里管理基于 {type} 的规则。',
> 您可以在这里管理基于地理的规则

> 您可以在这里管理基于名称的规则

> 您可以在这里管理基于 名称 的规则

我不喜欢这种空格

2024-12-30 08:38 UTC, Gaojianli commented
其他类似问题不重复了，为了避免空格相关内容阻塞合入，建议拆分为不同的PR

2024-12-30 08:56 UTC, CreeperAWA commented on webui/src/views/charts/locale/zh-CN.ts
> +  'page.charts.title.geoip': '位置与运营商 ',
这个是为了适应后面的括号，因为后面过滤器的括号是一个英文括号，我现在将过滤器的括号改为了中文括号

2024-12-30 08:58 UTC, CreeperAWA commented on webui/src/views/data-view/torrentList/locale/zh-CN.ts
> -    '从开始或者上次对端重置数据后，上传/下载数据增量信息',
『盘古之白』是这样的

2024-12-30 09:01 UTC, CreeperAWA commented on webui/src/views/dashboard/locale/zh-CN.ts
74~79行  
```
"page.dashboard.peerList.column.flags.d": "您：期待下载 ╱ 他：拒绝上传",
  "page.dashboard.peerList.column.flags.D": "您：期待下载 ╱ 他：同意上传",
  "page.dashboard.peerList.column.flags.u": "他：期待下载 ╱ 您：拒绝上传",
  "page.dashboard.peerList.column.flags.U": "他：期待下载 ╱ 您：同意上传",
  "page.dashboard.peerList.column.flags.K": "您：不想下载 ╱ 他：同意上传",
  "page.dashboard.peerList.column.flags.?": "他：不想下载 ╱ 您：同意上传",
```

2024-12-30 09:04 UTC, CreeperAWA commented on webui/src/locale/zh-CN.ts
> +  'service.networkErrorRetry.second': '{count} 秒',
『盘古之白』是这样的

2024-12-30 09:42 UTC, Gaojianli commented
鉴于此PR修改的方式存在盲目，机械的情况（例如 QQ旋风， slash两边增加空格），且并没有说明相关理由，存在脚本自动化替换的可能。此外进行的变更多数只是进行一些“无害”的空格添加，仔细Review会造成人力成本浪费，因此将不再接受类似简单增加空格的修改。以后的变更也注意单次提交的体积

2024-12-30 09:42 UTC, closed without merging